service: serverless-node-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: employee/create.create
    events:
      - http:
          path: employees/create
          method: post
          cors: true

  list:
    handler: employee/list.list
    events:
      - http:
          path: employees
          method: get
          cors: true

  get:
    handler: employee/get.get
    events:
      - http:
          path: employees/{id}
          method: get
          cors: true

  update:
    handler: employee/update.update
    events:
      - http:
          path: employees/{id}/update
          method: put
          cors: true

  delete:
    handler: employee/delete.delete
    events:
      - http:
          path: employees/{id}/delete
          method: delete
          cors: true

resources:
  Resources:
    EmployeeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
